[W-11308473] Async api headers
advanced-rest-client/api-method-documentation pull request #70
Opened 2022-06-22 14:38 UTC by carowright

Bug: AsyncAPI operation headers not being rendered

2022-06-22 19:00 UTC, TwoPlusTwoOne requested changes

2022-06-22 19:00 UTC, twoplustwoone commented on demo/index.js
> +      ['streetlights', 'streetlights'],
This should probably not be changed

2022-06-22 19:03 UTC, carowright commented on demo/index.js
> +      ['streetlights', 'streetlights'],
yep, my bad

2022-06-22 20:09 UTC, TwoPlusTwoOne approved these changes, later dismissed

2022-06-23 16:46 UTC, TwoPlusTwoOne approved these changes

2022-06-23 17:46 UTC, merged